const pptxgen = require('pptxgenjs');
const QRCode = require('qrcode');
const path = require('path');
const fs = require('fs');
const JSZip = require('jszip');

const pptx = new pptxgen();
pptx.layout = 'LAYOUT_WIDE';
pptx.author = 'Team Orion MIS';
pptx.subject = 'ORION MIS — University Management Information System';
pptx.title = 'ORION MIS | Final Year Project';
pptx.company = 'Team Orion MIS';
pptx.lang = 'en-IN';
pptx.theme = {
  headFontFace: 'Poppins', bodyFontFace: 'Inter', lang: 'en-IN'
};
pptx.defineLayout({ name:'CUSTOM_WIDE', width:13.333, height:7.5 });
pptx.layout = 'CUSTOM_WIDE';
pptx.defineSlideMaster({
  title: 'ORION', background: { color: '0B0F19' },
  objects: [
    { rect: { x:0, y:0, w:13.333, h:0.045, fill:{color:'5DE4FF',transparency:35}, line:{color:'5DE4FF',transparency:100} } },
    { text: { text:'ORION  /  UNIVERSITY MANAGEMENT INFORMATION SYSTEM', options:{ x:0.48,y:7.14,w:7,h:0.18,fontFace:'Inter',fontSize:5.7,color:'8291AD',charSpacing:1.2,margin:0 } } },
    { text: { text:'FINAL YEAR PROJECT  •  2026', options:{ x:10.0,y:7.14,w:2.85,h:0.18,fontFace:'Inter',fontSize:5.7,color:'8291AD',align:'right',charSpacing:0.7,margin:0 } } }
  ],
  slideNumber: { x:12.88, y:7.13, color:'8291AD', fontFace:'Inter', fontSize:5.7 }
});

const C={bg:'0B0F19',deep:'10182B',panel:'15213A',blue:'3D8BFF',cyan:'5DE4FF',purple:'8D5BFF',violet:'C46CFF',white:'F5F8FF',muted:'A5B4CF',line:'315079',green:'59E6B7',red:'FF737D',yellow:'FFD36A'};
const S=pptx.ShapeType;
function t(slide, text, x,y,w,h,opts={}){ slide.addText(text,{x,y,w,h,margin:0,breakLine:false,fontFace:opts.fontFace||'Inter',fontSize:opts.fontSize||12,color:opts.color||C.white,bold:opts.bold||false,align:opts.align||'left',valign:opts.valign||'mid',fit:'shrink',charSpacing:opts.charSpacing,italic:opts.italic,paraSpaceAfterPt:0,bullet:opts.bullet}); }
function rect(slide,x,y,w,h,fill=C.panel,trans=0,r=0.16,line=C.line){ slide.addShape(r?S.roundRect:S.rect,{x,y,w,h,rectRadius:r,fill:{color:fill,transparency:trans},line:{color:line,transparency:line?65:100,width:0.6},shadow:{type:'outer',color:'000000',opacity:0.20,blur:2,angle:45,distance:1}}); }
function line(slide,x1,y1,x2,y2,color=C.cyan,width=1,dash='solid'){slide.addShape(S.line,{x:x1,y:y1,w:x2-x1,h:y2-y1,line:{color,width,dashType:dash,beginArrowType:'none',endArrowType:'triangle'}});}
function dot(slide,x,y,color=C.cyan,size=.08){slide.addShape(S.ellipse,{x,y,w:size,h:size,fill:{color},line:{color,transparency:100},shadow:{type:'outer',color,opacity:.75,blur:2,distance:0}});}
function pill(slide,text,x,y,w,color=C.blue){rect(slide,x,y,w,.27,color,70,.13,color);t(slide,text,x+.1,y+.045,w-.2,.13,{fontSize:5.7,color:C.white,bold:true,align:'center',charSpacing:.5});}
function title(slide,eyebrow,heading,sub){t(slide,eyebrow.toUpperCase(),.55,.42,7,.18,{fontSize:6.8,color:C.cyan,bold:true,charSpacing:1.9});t(slide,heading,.55,.68,11.8,.48,{fontFace:'Poppins',fontSize:24,color:C.white,bold:true});if(sub)t(slide,sub,.56,1.23,11.4,.33,{fontSize:8.2,color:C.muted});}
function glow(slide,x,y,w,h,color=C.purple){slide.addShape(S.ellipse,{x,y,w,h,fill:{color,transparency:75},line:{color,transparency:100}});}
function bg(slide){glow(slide,9.2,-1.2,5.2,5.2,C.purple);glow(slide,-2.1,4.3,5.6,3.5,C.blue);for(let i=0;i<17;i++){const x=.25+(i*1.07)%12.5,y=1.6+((i*1.73)%5.1); dot(slide,x,y,i%3?C.blue:C.purple,.025);}}
function card(slide,x,y,w,h,label,value,accent=C.cyan){rect(slide,x,y,w,h,C.panel,10,.16,accent);slide.addShape(S.rect,{x,y,w:.035,h,fill:{color:accent},line:{color:accent,transparency:100}});t(slide,label,x+.18,y+.16,w-.35,.16,{fontSize:6,color:C.muted,bold:true,charSpacing:.7});t(slide,value,x+.18,y+.43,w-.34,h-.5,{fontFace:'Poppins',fontSize:15,color:C.white,bold:true});}
function icon(slide,kind,x,y,s=0.35,color=C.cyan){ const base={fill:{color,transparency:84},line:{color,width:1}}; if(kind==='cloud'){slide.addShape(S.arc,{x,y:y+.1,w:s,h:s*.42,adjustPoint:.3,line:{color,width:1.2},fill:{color,transparency:100}});slide.addShape(S.ellipse,{x:x+s*.26,y,w:s*.35,h:s*.35,...base});slide.addShape(S.ellipse,{x:x+s*.53,y:y+.08,w:s*.32,h:s*.32,...base});}else if(kind==='user'){slide.addShape(S.ellipse,{x:x+s*.33,y,w:s*.34,h:s*.34,...base});slide.addShape(S.arc,{x:x+s*.16,y:y+s*.32,w:s*.68,h:s*.45,adjustPoint:.2,line:{color,width:1.1},fill:{color,transparency:100}});}else if(kind==='shield'){slide.addShape(S.chevron,{x,y,w:s,h:s*1.1,rotate:90,fill:{color,transparency:84},line:{color,width:1.1}});}else if(kind==='db'){slide.addShape(S.can,{x,y,w:s,h:s*.9,fill:{color,transparency:84},line:{color,width:1.1}});}else if(kind==='code'){t(slide,'</>',x,y,s,.28,{fontFace:'Montserrat',fontSize:10,color,bold:true,align:'center'});}else{slide.addShape(S.ellipse,{x,y,w:s,h:s,...base});} }
function node(slide,label,x,y,w=1.45,h=.52,color=C.blue,ico='code'){rect(slide,x,y,w,h,C.panel,4,.14,color);icon(slide,ico,x+.12,y+.13,.22,color);t(slide,label,x+.42,y+.145,w-.5,.15,{fontSize:6.8,bold:true,color:C.white});}
function notes(slide,txt){slide.addNotes(txt);}

// 1
{let s=pptx.addSlide('ORION');bg(s);glow(s,5.0,.1,4.3,4.3,C.purple);t(s,'ORION MIS',.62,1.36,7.4,.72,{fontFace:'Poppins',fontSize:35,bold:true,color:C.white});t(s,'University Management Information System',.65,2.15,6.4,.36,{fontSize:14,color:C.cyan,bold:true});t(s,'MODERN CLOUD-NATIVE ARCHITECTURE',.66,2.70,4.7,.18,{fontSize:6.5,color:C.muted,bold:true,charSpacing:1.5});pill(s,'AGILE',.66,3.15,.78,C.blue);pill(s,'DEVOPS',1.52,3.15,.9,C.purple);pill(s,'DOCKER',2.5,3.15,.95,C.cyan);pill(s,'AWS',3.53,3.15,.65,C.violet);
// 3D university / connected cloud
rect(s,7.15,2.1,4.9,2.8,'111D35',8,.26,C.cyan);t(s,'LIVE UNIVERSITY OPERATIONS',7.48,2.35,3.6,.2,{fontSize:6.5,color:C.muted,bold:true,charSpacing:1});
// buildings
for(let i=0;i<4;i++){const bx=7.65+i*.76, bh=.68+(i%3)*.35;s.addShape(S.rect,{x:bx,y:4.45-bh,w:.54,h:bh,fill:{color:i%2?C.blue:C.purple,transparency:15},line:{color:C.cyan,transparency:40}});for(let z=0;z<3;z++)s.addShape(S.rect,{x:bx+.11,y:4.55-bh+z*.22,w:.09,h:.07,fill:{color:C.cyan},line:{color:C.cyan,transparency:100}});}
icon(s,'cloud',10.55,2.88,.78,C.cyan);node(s,'Dashboard',8.0,5.1,1.45,.55,C.cyan,'code');node(s,'Server',9.65,5.1,1.25,.55,C.purple,'db');node(s,'Network',11.08,5.1,1.15,.55,C.blue,'cloud');line(s,8.75,4.5,10.92,3.65,C.cyan,.8);line(s,9.1,5.1,9.9,4.45,C.purple,.8);line(s,10.3,5.1,10.9,4.15,C.blue,.8);t(s,'A single intelligent fabric for academic excellence.',.66,5.8,5.9,.3,{fontSize:10,color:C.muted,italic:true});notes(s,'Open with the ORION MIS vision: one cloud-native platform that connects university operations end-to-end.');}

// 2
{let s=pptx.addSlide('ORION');bg(s);title(s,'01 / Project overview','One intelligent operating system for campus life','A unified, role-aware platform that makes academic operations visible, actionable and secure.');const modules=[['Student Management','user',C.cyan],['Faculty Management','user',C.purple],['Attendance','code',C.green],['Courses','code',C.blue],['Departments','cloud',C.violet],['Examination','shield',C.yellow],['Results','db',C.cyan],['Reports','code',C.purple],['Role Based Access','shield',C.green]];modules.forEach((m,i)=>{let x=.62+(i%3)*4.15,y=2.0+Math.floor(i/3)*1.37;rect(s,x,y,3.7,1.04,C.panel,8,.18,m[2]);icon(s,m[1],x+.23,y+.26,.38,m[2]);t(s,m[0],x+.75,y+.23,2.7,.2,{fontSize:10,bold:true});t(s,['Profiles & lifecycle','Workloads & allocation','Live academic signals','Catalog & credits','Structured governance','Schedules & assessments','Grades & insight','PDF / Excel intelligence','Least-privilege controls'][i],x+.75,y+.55,2.6,.14,{fontSize:6.3,color:C.muted});});notes(s,'Explain that every module shares a common identity, data model and reporting layer.');}

// 3
{let s=pptx.addSlide('ORION');bg(s);title(s,'02 / Problem statement','From fragmented effort to a connected campus','Traditional processes introduce latency, blind spots and avoidable security risk.');rect(s,.62,2,5.65,4.3,'161826',7,.22,C.red);rect(s,7.08,2,5.65,4.3,'102238',6,.22,C.cyan);t(s,'TRADITIONAL SYSTEM',.95,2.36,4.8,.22,{fontSize:9,bold:true,color:C.red,charSpacing:1.2});t(s,'ORION MIS',7.42,2.36,4.8,.22,{fontSize:9,bold:true,color:C.cyan,charSpacing:1.2});const left=['Paper-based operations','Manual attendance','Slow report generation','Poor communication','Siloed management','Security gaps'];const right=['Digital workflows','Real-time attendance','Instant reports','Unified updates','Central command center','Protected by design'];left.forEach((v,i)=>{let y=2.86+i*.49;dot(s,1.0,y+.08,C.red,.09);t(s,v,1.22,y,4.4,.17,{fontSize:8.3,color:C.muted});dot(s,7.48,y+.08,C.green,.09);t(s,right[i],7.7,y,4.4,.17,{fontSize:8.3,color:C.white});});s.addShape(S.chevron,{x:6.33,y:3.58,w:.65,h:.42,fill:{color:C.purple},line:{color:C.cyan,width:1},shadow:{type:'outer',color:C.purple,opacity:.65,blur:5,distance:0}});t(s,'VS',6.42,3.7,.43,.12,{fontSize:6,bold:true,align:'center'});notes(s,'Frame the project as a transformation: manual systems lose time and control; ORION makes operations digital, auditable and responsive.');}

// 4
{let s=pptx.addSlide('ORION');bg(s);title(s,'03 / Project vision','Build the university platform that evolves with ambition','Secure. Scalable. Insightful. Continuously delivered.');const items=[['Automate','Academic & administrative workflows',C.cyan],['Protect','Role-based access & auditability',C.purple],['Scale','Cloud-native infrastructure',C.blue],['Illuminate','Analytics for better decisions',C.green],['Deliver','Continuous deployment',C.violet]];items.forEach((a,i)=>{let x=.7+i*2.5;glow(s,x+.3,2.15,.95,.95,a[2]);s.addShape(S.ellipse,{x:x+.55,y:2.6,w:.28,h:.28,fill:{color:a[2]},line:{color:a[2],transparency:100}});if(i<4)line(s,x+1.0,2.73,x+2.35,2.73,C.line,.9);rect(s,x,3.35,2.05,1.7,C.panel,6,.17,a[2]);t(s,a[0],x+.2,3.7,1.6,.2,{fontSize:10,bold:true,color:a[2],align:'center'});t(s,a[1],x+.22,4.15,1.62,.37,{fontSize:7,color:C.muted,align:'center'});});t(s,'Roadmap principle  →  ship valuable increments, measure impact, improve continuously.',1.38,5.8,10.5,.22,{fontSize:9,color:C.white,align:'center',italic:true});notes(s,'Connect the vision to the roadmap: deliver usable increments through Agile sprints and continuously improve based on feedback.');}

// 5
{let s=pptx.addSlide('ORION');bg(s);title(s,'04 / Technology stack','A modern stack, layered for velocity and resilience','Each layer is purpose-built, from fluid interfaces to secure infrastructure.');const layers=[['FRONTEND','React 19  •  Vite  •  Tailwind CSS  •  React Router  •  Framer Motion  •  Axios  •  React Hook Form  •  Joi  •  Chart.js',C.cyan],['BACKEND','Node.js  •  Express.js  •  JWT  •  Swagger  •  PDFKit  •  ExcelJS',C.purple],['DATA','MySQL 8  •  Sequelize ORM',C.blue],['CLOUD','Docker  •  Docker Compose  •  Terraform  •  AWS EC2  •  Render',C.green],['DEVOPS','GitHub Actions  •  Nginx  •  Helmet  •  Trivy  •  Rate Limiting',C.violet]];layers.forEach((a,i)=>{let y=1.85+i*.84,x=1.08+i*.22,w=11.2-i*.44;rect(s,x,y,w,.6,C.panel,8,.12,a[2]);t(s,a[0],x+.25,y+.19,1.2,.14,{fontSize:6.8,bold:true,color:a[2],charSpacing:1});t(s,a[1],x+1.62,y+.17,w-1.9,.18,{fontSize:7,color:C.white});});t(s,'Experience',.66,2.06,.35,.15,{fontSize:5.5,color:C.muted,rotate:270});t(s,'Security + observability embedded across every layer',3.1,6.35,7.2,.2,{fontSize:8,color:C.muted,align:'center'});notes(s,'Walk top-down: React drives the experience; Express encapsulates APIs; MySQL provides reliable data; Docker and Terraform make cloud deployment repeatable.');}

// 6 workflow
{let s=pptx.addSlide('ORION');bg(s);title(s,'05 / Complete system workflow','Every interaction becomes a secure, visible outcome','A request travels through a controlled path—then returns as a live dashboard update.');const flow=[['Student / Faculty / Admin','user',C.cyan],['Login','shield',C.purple],['JWT Authentication','shield',C.blue],['React Frontend','code',C.cyan],['Axios API Requests','code',C.violet],['Express REST API','code',C.blue],['Business Logic','code',C.purple],['MySQL Database','db',C.green],['Response','code',C.cyan],['Dashboard Updates','code',C.yellow]];flow.forEach((a,i)=>{let col=i<5?0:1,row=i<5?i:i-5,x=2.0+col*5.35,y=1.85+row*.89;node(s,a[0],x,y,3.05,.54,a[2],a[1]);if(row<4)line(s,x+1.52,y+.54,x+1.52,y+.84,a[2],1);});line(s,5.05,5.95,7.25,1.85,C.cyan,1.2);for(let i=0;i<10;i++)dot(s,5.55+i*.14,5.34-i*.28,i%2?C.cyan:C.purple,.055);pill(s,'LIVE API PARTICLES',8.8,6.23,1.45,C.purple);notes(s,'Trace a typical role-based request: identity, JWT, UI, Axios, API, business logic, database, response and dashboard.');}

// 7 arch
{let s=pptx.addSlide('ORION');bg(s);title(s,'06 / Overall system architecture','Clear separation of concerns, seamless delivery of value','Core layers are compact, testable and independently understandable.');const layers=[['USERS','Student  •  Faculty  •  Admin','user',C.cyan],['REACT FRONTEND','Dashboards • Routing • Forms','code',C.blue],['EXPRESS REST API','Endpoints • JWT • Swagger','code',C.purple],['BUSINESS LOGIC','Policies • Workflows • Reports','code',C.violet],['SEQUELIZE ORM','Models • Queries • Validation','db',C.green],['MYSQL DATABASE','Normalized academic data','db',C.cyan]];layers.forEach((a,i)=>{let y=1.75+i*.69;node(s,a[0],1.02,y,2.4,.48,a[3],a[2]);t(s,a[1],3.68,y+.16,2.5,.13,{fontSize:6.6,color:C.muted});if(i<5)line(s,2.22,y+.48,2.22,y+.66,a[3],.8);});rect(s,7.4,1.75,4.9,4.2,'111D35',6,.2,C.line);t(s,'SIDE CAPABILITIES',7.78,2.06,3.8,.18,{fontSize:7,color:C.muted,bold:true,charSpacing:1.2});[['React Hook Form','Validation',C.cyan],['PDFKit','Report generation',C.purple],['ExcelJS','Excel export',C.green]].forEach((a,i)=>{let y=2.65+i*1.0;node(s,a[0],7.82,y,1.65,.48,a[2],'code');line(s,9.5,y+.24,10.08,y+.24,a[2],.8);t(s,a[1],10.28,y+.16,1.55,.13,{fontSize:6.5,color:C.white});});notes(s,'This is the application architecture: a client layer, controlled REST API, business logic, ORM and normalized database—with focused supporting services.');}

// 8 cloud
{let s=pptx.addSlide('ORION');bg(s);title(s,'07 / Cloud infrastructure architecture','Infrastructure as code, repeatable from commit to cloud','An AWS-style deployment path designed for control, isolation and scale.');const flow=[['Developer','user',C.cyan],['GitHub','code',C.white],['GitHub Actions','code',C.purple],['Docker Build','code',C.blue],['Docker Compose','code',C.cyan],['Terraform','code',C.violet],['AWS EC2','cloud',C.yellow],['Nginx','code',C.green],['React + Express','code',C.cyan],['MySQL','db',C.blue]];flow.forEach((a,i)=>{let x=.68+i*1.22;node(s,a[0],x,2.1,1.03,.5,a[3],a[1]);if(i<9)line(s,x+1.03,2.35,x+1.2,2.35,a[3],.65);});rect(s,3.05,3.35,7.25,2.35,'111D35',4,.24,C.yellow);t(s,'AWS EC2 / PRODUCTION VPC',3.38,3.68,3.5,.2,{fontSize:8,bold:true,color:C.yellow,charSpacing:1.1});[['Elastic IP',3.45,4.26,C.cyan],['Security Groups',5.06,4.26,C.purple],['Docker Network',7.05,4.26,C.green],['Volumes',8.85,4.26,C.blue],['Environment Variables',4.18,5.0,C.violet],['HTTPS + Monitoring',7.55,5.0,C.yellow]].forEach(a=>{pill(s,a[0],a[1],a[2],a[0].length*.057+.53,a[3]);});t(s,'Cloud boundary',10.55,4.35,1.1,.12,{fontSize:6,color:C.muted,rotate:270});notes(s,'Explain the deployment route: source control triggers CI, Docker packages services, Terraform declares infrastructure, and EC2 serves the stack behind Nginx.');}

// 9 devops
{let s=pptx.addSlide('ORION');bg(s);title(s,'08 / DevOps deployment workflow','From a developer push to a protected production release','Continuous integration turns delivery into a governed, repeatable pipeline.');const p=[['Developer','user',C.cyan],['Git Push','code',C.blue],['GitHub Repo','code',C.white],['GitHub Actions','code',C.purple],['Automated Testing','shield',C.green],['Docker Image','code',C.cyan],['Trivy Scan','shield',C.red],['Terraform','code',C.violet],['AWS Deploy','cloud',C.yellow],['Nginx','code',C.green],['Production','cloud',C.cyan],['End Users','user',C.blue]];p.forEach((a,i)=>{let x=.58+(i%6)*2.12,y=1.95+Math.floor(i/6)*2.0;node(s,a[0],x,y,1.72,.58,a[3],a[1]);if(i%6<5)line(s,x+1.72,y+.29,x+2.04,y+.29,a[3],1);});line(s,11.15,2.53,11.15,3.9,C.cyan,1);pill(s,'CI',1.05,5.4,.5,C.purple);pill(s,'SECURITY GATE',3.0,5.4,1.3,C.red);pill(s,'CD',5.7,5.4,.5,C.cyan);pill(s,'OBSERVABLE PRODUCTION',7.25,5.4,1.85,C.green);t(s,'Automated checks make release velocity safe.',3.0,6.12,7.3,.2,{fontSize:9,color:C.muted,align:'center'});notes(s,'Stress that security is a gate, not an afterthought: tests and Trivy scanning occur before infrastructure and production rollout.');}

// 10 ER
{let s=pptx.addSlide('ORION');bg(s);title(s,'09 / Database model','A normalized academic data model built for traceability','Core relationships keep people, programs, participation and performance connected.');const es=[['Users',1.1,2.0,C.cyan],['Students',.7,3.25,C.blue],['Faculty',2.2,3.25,C.purple],['Departments',4.5,2.0,C.green],['Courses',4.7,3.45,C.yellow],['Course Offerings',6.72,3.45,C.violet],['Enrollments',8.78,2.35,C.cyan],['Attendance',10.85,1.75,C.green],['Exams',8.95,4.6,C.purple],['Results',10.95,4.55,C.blue]];es.forEach(a=>node(s,a[0],a[1],a[2],1.35,.5,a[3],a[0]==='Users'?'shield':'db'));const con=[[2.45,2.25,1.38,3.25],[2.45,2.25,2.88,3.25],[3.58,3.5,4.7,3.7],[5.85,3.7,6.72,3.7],[8.07,3.7,8.78,2.6],[10.13,2.6,10.85,2.0],[10.13,2.6,8.95,4.85],[10.3,4.85,10.95,4.8],[7.38,3.95,9.1,4.6]];con.forEach((a,i)=>line(s,...a,i%2?C.purple:C.cyan,.8));t(s,'1 : 1',2.5,2.56,.35,.1,{fontSize:5,color:C.muted});t(s,'1 : *',6.0,3.78,.35,.1,{fontSize:5,color:C.muted});t(s,'Color-coded entities • glowing relations • normalized core',3.35,6.25,6.7,.18,{fontSize:8,color:C.muted,align:'center'});notes(s,'The ER model is centered on users and departments. Offerings connect courses to faculty, while enrollments, attendance, exams and results capture the student journey.');}

// 11 agile
{let s=pptx.addSlide('ORION');bg(s);title(s,'10 / Agile development lifecycle','A sprint rhythm that keeps value moving','The roadmap converts priorities into working increments, feedback and continuous improvement.');const phases=[['Product\nBacklog',C.cyan],['Sprint\nPlanning',C.blue],['Development',C.purple],['Testing',C.green],['Sprint\nReview',C.yellow],['Deployment',C.violet],['Continuous\nImprovement',C.cyan]];phases.forEach((a,i)=>{let x=.65+i*1.77;glow(s,x-.05,2.1,1.35,1.35,a[1]);s.addShape(S.ellipse,{x:x+.25,y:2.5,w:.72,h:.72,fill:{color:C.panel},line:{color:a[1],width:1.5}});t(s,String(i+1),x+.25,2.7,.72,.16,{fontSize:10,bold:true,color:a[1],align:'center'});t(s,a[0],x,3.55,1.25,.4,{fontSize:7,bold:true,color:C.white,align:'center'});if(i<6)line(s,x+1.0,2.86,x+1.7,2.86,a[1],1);});rect(s,1.2,5.1,10.8,.75,'111D35',5,.18,C.line);t(s,'SPRINT BOARD',1.52,5.39,1.25,.14,{fontSize:6.4,color:C.muted,bold:true,charSpacing:1});['Prioritized work','Daily visibility','Working increment','Feedback loop'].forEach((v,i)=>pill(s,v,3.05+i*2.1,5.32,1.65,[C.cyan,C.blue,C.purple,C.green][i]));notes(s,'Show how the roadmap becomes delivery: backlog to planning, development, testing, review, deployment and improvement, repeating every sprint.');}

// 12 team
{let s=pptx.addSlide('ORION');bg(s);title(s,'11 / Team responsibilities','Five specialists, one shared mission','A cross-functional team owns the full journey from interaction design to dependable operations.');const people=[['Dhruv Mohapatro','FRONTEND LEAD','React • Tailwind • Framer Motion • Dashboards • UI/UX',C.cyan,'code'],['Jay Krishna Rout','BACKEND LEAD','Express • REST APIs • JWT • Swagger • Business Logic',C.purple,'code'],['Biswajit Barik','DATABASE LEAD','MySQL • Sequelize • ER Design • Query Optimization',C.green,'db'],['Arab Das','CLOUD INFRASTRUCTURE & CONTAINERIZATION','Docker • Docker Compose • Terraform • AWS EC2 • IaC • Render • Cloud Architecture',C.yellow,'cloud'],['Surya Kanta Lenka','DEVOPS, SECURITY & DEPLOYMENT','GitHub Actions • CI/CD • Nginx • SSL • Helmet • Trivy • Rate Limiting',C.violet,'shield']];people.forEach((a,i)=>{let x=.64+(i%3)*4.1,y=1.9+Math.floor(i/3)*2.05,w=i===3||i===4?5.88:3.75; if(i===4)x=6.8;rect(s,x,y,w,1.63,C.panel,i===3?0:7,.22,a[3]);icon(s,a[4],x+.23,y+.28,.43,a[3]);t(s,a[0],x+.78,y+.23,w-.95,.2,{fontSize:9,bold:true});t(s,a[1],x+.24,y+.84,w-.48,.14,{fontSize:5.8,color:a[3],bold:true,charSpacing:.8});t(s,a[2],x+.24,y+1.13,w-.48,.26,{fontSize:6.6,color:C.muted});if(i===3){pill(s,'CLOUD LEAD',x+w-1.38,y+.27,1.08,C.yellow);}});notes(s,'Introduce the team as a complete product team. Highlight Arab Das as owner of cloud infrastructure and containerization.');}

// 13 security
{let s=pptx.addSlide('ORION');bg(s);title(s,'12 / Security architecture','Security is designed into every request','Layered defenses protect identities, traffic, APIs and operating infrastructure.');glow(s,4.65,1.65,4.1,4.1,C.purple);icon(s,'shield',5.72,2.25,1.65,C.cyan);t(s,'PROTECTED\nORION PLATFORM',4.6,4.15,4,.48,{fontFace:'Poppins',fontSize:15,bold:true,align:'center'});const sec=[['JWT Authentication',1.0,2.0,C.cyan],['RBAC',1.0,4.75,C.purple],['Helmet',3.3,5.7,C.green],['HTTPS',8.9,5.7,C.cyan],['CORS',10.6,4.75,C.blue],['Rate Limiting',10.0,2.0,C.red],['Audit Logs',8.95,1.25,C.yellow],['Vulnerability Scanning',2.75,1.25,C.violet]];sec.forEach(a=>{pill(s,a[0],a[1],a[2],a[0].length*.06+.52,a[3]);line(s,a[1]+.3,a[2]+.27,6.55,3.55,a[3],.55);});notes(s,'Explain defense in depth: identity, access, safe headers, encrypted transport, CORS, rate controls, auditability and vulnerability scanning.');}

// 14 future
{let s=pptx.addSlide('ORION');bg(s);title(s,'13 / Future scope','The next horizon for an intelligent campus','A future-ready foundation can welcome new intelligence, channels and automation.');const fs=[['AI Chatbot','Conversational campus help',C.cyan],['Face Recognition','Attendance intelligence',C.purple],['Mobile App','Campus in every pocket',C.blue],['Predictive Analytics','Early insight, better action',C.green],['Cloud Auto Scaling','Elastic performance',C.yellow],['LMS Integration','Connected learning',C.violet],['Smart Notifications','Right message, right moment',C.cyan]];fs.forEach((a,i)=>{let x=.75+(i%4)*3.12,y=1.95+Math.floor(i/4)*2.1;rect(s,x,y,2.62,1.55,C.panel,8,.18,a[2]);glow(s,x+.12,y+.12,.72,.72,a[2]);icon(s,i===1?'user':i===4?'cloud':'code',x+.28,y+.32,.3,a[2]);t(s,a[0],x+.25,y+.83,2.05,.18,{fontSize:8.2,bold:true});t(s,a[1],x+.25,y+1.15,2.0,.16,{fontSize:6.2,color:C.muted});});notes(s,'Position these as credible next steps, enabled by the present architecture: AI assistance, smart attendance, mobile, predictive insights and elastic cloud capacity.');}

// 15 impact
{let s=pptx.addSlide('ORION');bg(s);title(s,'14 / Expected benefits & impact','Measure what matters. Improve what matters.','The roadmap’s outcomes become practical value for administrators, faculty and students.');const k=[['FASTER','Administration',C.cyan],['LESS','Manual work',C.purple],['SECURE','Role-based access',C.green],['ELASTIC','Cloud scalability',C.blue],['LIVE','Analytics',C.yellow],['BETTER','Student experience',C.violet],['AUTOMATED','Reporting',C.cyan],['SMARTER','Decision making',C.green]];k.forEach((a,i)=>{let x=.7+(i%4)*3.1,y=1.95+Math.floor(i/4)*1.8;card(s,x,y,2.6,1.35,a[1],a[0],a[2]);});notes(s,'The expected impact is operational: faster administration and reports, less manual effort, protected access, scalable delivery and better decisions through real-time analytics.');}

// 16 demo
{let s=pptx.addSlide('ORION');bg(s);title(s,'15 / Live demo','Experience ORION across every role','Use the live walkthrough to prove the flow from access to insight.');const screens=[['Login Screen',.72,2.05,C.cyan],['Student Dashboard',3.17,2.05,C.blue],['Faculty Dashboard',5.62,2.05,C.purple],['Admin Dashboard',8.07,2.05,C.violet],['Attendance Module',2.0,4.62,C.green],['Results Module',5.0,4.62,C.yellow],['Analytics Dashboard',8.0,4.62,C.cyan]];screens.forEach((a,i)=>{let w=i<4?2.05:2.35,h=i<4?1.63:1.12;rect(s,a[1],a[2],w,h,'111D35',3,.15,a[3]);s.addShape(S.roundRect,{x:a[1]+.18,y:a[2]+.23,w:w-.36,h:h-.55,rectRadius:.08,fill:{color:'172C4A'},line:{color:a[3],transparency:55,width:.6}});s.addShape(S.rect,{x:a[1]+.32,y:a[2]+.42,w:(w-.64)*.65,h:.09,fill:{color:a[3]},line:{color:a[3],transparency:100}});for(let z=0;z<3;z++)s.addShape(S.rect,{x:a[1]+.32,y:a[2]+.63+z*.18,w:(w-.64)*(z===1?.82:.52),h:.065,fill:{color:'567197'},line:{color:'567197',transparency:100}});t(s,a[0],a[1]+.14,a[2]+h-.2,w-.28,.12,{fontSize:5.8,color:C.white,bold:true,align:'center'});});t(s,'Suggested sequence  →  login  →  role dashboard  →  attendance / results  →  analytics',1.5,6.42,10.3,.18,{fontSize:8.5,color:C.muted,align:'center'});notes(s,'For the demo, use these exact stops: login, student dashboard, faculty dashboard, admin dashboard, attendance, results and analytics.');}

// 17 github
{let s=pptx.addSlide('ORION');bg(s);title(s,'16 / GitHub repository','A repository organized for confident contribution','Structure, tooling and workflow make the project approachable for every contributor.');rect(s,.7,1.92,6.55,4.35,'111D35',5,.18,C.line);t(s,'PROJECT STRUCTURE',1.05,2.25,2.8,.18,{fontSize:7,color:C.muted,bold:true,charSpacing:1});const tree=['/ frontend','  ├─ src / components / pages','  ├─ hooks / services / assets','/ backend','  ├─ controllers / models / routes','  ├─ middleware / services / docs','/ nginx','/ terraform','/ .github / workflows'];tree.forEach((v,i)=>t(s,v,1.16,2.72+i*.32,4.6,.14,{fontFace:'Consolas',fontSize:7,color:i===0||i===3?C.cyan:C.muted,bold:i===0||i===3}));rect(s,7.65,1.92,4.97,4.35,C.panel,6,.18,C.white);t(s,'DEVELOPMENT FLOW',7.98,2.26,2.8,.18,{fontSize:7,color:C.muted,bold:true,charSpacing:1});['Branch → Build → Review','CI checks → Security scan','Deploy → Monitor → Improve'].forEach((v,i)=>{pill(s,v,8.02,2.75+i*.55,2.35,[C.blue,C.purple,C.green][i]);});t(s,'REPOSITORY QR',10.72,3.25,1.35,.13,{fontSize:5.3,color:C.muted,align:'center',charSpacing:.8});s.addShape(S.rect,{x:10.85,y:3.48,w:1.1,h:1.1,fill:{color:'F5F8FF'},line:{color:C.cyan,width:1}});t(s,'QR',11.03,3.88,.75,.18,{fontFace:'Poppins',fontSize:12,bold:true,color:C.bg,align:'center'});t(s,'Replace with repository URL',9.9,5.0,3,.14,{fontSize:6,color:C.muted,align:'center'});notes(s,'Show the project layout, key technologies and contribution workflow. Replace the QR placeholder with the final GitHub repository link before presentation.');}

// 18
{let s=pptx.addSlide('ORION');bg(s);glow(s,4.6,.45,4.2,4.2,C.purple);t(s,'THANK YOU',2.25,1.4,8.8,.55,{fontFace:'Poppins',fontSize:34,bold:true,align:'center'});t(s,'Team Orion MIS',3.35,2.18,6.6,.25,{fontSize:14,bold:true,color:C.cyan,align:'center'});t(s,'Questions?',4.57,2.94,4.2,.35,{fontFace:'Poppins',fontSize:18,bold:true,color:C.white,align:'center'});for(let i=0;i<6;i++){let x=2.7+i*1.25,hh=.55+(i%3)*.26;s.addShape(S.rect,{x,y:5.7-hh,w:.76,h:hh,fill:{color:i%2?C.blue:C.purple,transparency:20},line:{color:C.cyan,transparency:50}});}icon(s,'cloud',5.5,4.35,1.2,C.cyan);line(s,3.15,5.2,5.82,4.85,C.cyan,.8);line(s,9.9,5.2,6.55,4.85,C.purple,.8);t(s,'Cloud-native university operations, built to evolve.',2.9,6.35,7.6,.18,{fontSize:8.5,color:C.muted,align:'center'});notes(s,'Thank the audience, invite questions and transition into the demo or Q&A.');}

async function main(){
  const out=path.resolve(__dirname,'..','ORION_MIS_Final_Year_Project_Presentation.pptx');
  await pptx.writeFile({ fileName:out });
  // PptxGenJS creates the presentation; add a native PowerPoint fade transition
  // to every slide for a polished, keynote-style progression.
  const zip=await JSZip.loadAsync(fs.readFileSync(out));
  for(const name of Object.keys(zip.files).filter(n=>/^ppt\/slides\/slide\d+\.xml$/.test(n))){
    const file=zip.file(name);
    const xml=await file.async('string');
    if(!xml.includes('<p:transition')) zip.file(name,xml.replace('</p:sld>','<p:transition spd="slow" advClick="1"><p:fade/></p:transition></p:sld>'));
  }
  fs.writeFileSync(out,await zip.generateAsync({type:'nodebuffer',compression:'DEFLATE'}));
  console.log(out);
}
main().catch(e=>{console.error(e);process.exit(1);});
